### ISSUE TITLE
USB printer support

### ISSUE THREAD

**Issue by codeyash** [base4sistemas/pyescpos#12]
How to use a USB port based printer? I can't find any example using USB based printer implementation.

**Comment by danielgoncalves** [comment]
There is a branch named `usbif` with an implementation for USB connections that you can experiment with. BTW we need help to test and refine that code :smiley:

**Comment by jboyd79** [comment]
Hello,
The following worked for me on Ubuntu 20.04.1 LTS using an Epson TM-20 printer.
Note: I did not use the usbif branch:
```
from escpos.conn.usb import USBConnection
from escpos.impl.epson import TMT20
conn = USBConnection.create('04b8:0e03,interface=0,ep_out=1,ep_in=2')
printer = TMT20(conn)
printer.init()
printer.text('Hello World!')
```
