### ISSUE TITLE
Ability to switch code pages.

### ISSUE THREAD

**Issue by MeanEYE** [base4sistemas/pyescpos#15]
My printer M58-LL, and presumably many others, come with different code pages. These pages allow us to use other characters than Latin. Having ability to switch page would be very useful.

**Comment by danielgoncalves** [comment]
This year commits (master branch) we have added two keyword arguments for the `escpos.impl.epson.GenericESCPOS` called `encoding` and `encoding_errors` which defaults to `utf-8` and `strict` respectively.

If you're dealing with a CP855 code page enabled printer, you should instantiate it like so:

```python

from escpos import NetworkConnection
from escpos.impl.epson import TMT20

conn = NetworkConnection.create('192.168.1.100:9100')

printer = TMT20(conn, encoding='cp855', encoding_errors='ignore')
printer.init()
printer.text('Здраво Свете!')
printer.cut()
```

This feature will be in the next release.

**Comment by MeanEYE** [comment]
I reported this issue some time ago. Since then I have added support for code pages and switching them on the fly. Those changes are available as pull request on this project.

This implementation where encoding is specified upon printer initialization doesn't really work for me as I needed to switch between code pages while printing different parts. Obvious example for this is that not all code pages have line/box drawing characters and math symbols.

**Comment by danielgoncalves** [comment]
If I understood correctly, for line drawing and math characters you could use `printer.device.write(<bytes>)` without encoding (raw write, sort of). By the way, there is nothing really fancy about the `encoding` attribute, so you can modify encoding just before calling any print methods.

Otherwise, if the above does not work, can you give me an example of how that API could be?

**Comment by danielgoncalves** [comment]
I just saw your pull request. You mean change **the printer codepage**. I've reviewed your pr. Thanks.

**Comment by MeanEYE** [comment]
Yes, sorry for lack of clarity. That's what I meant.
