### ISSUE TITLE
Aligning texts on single line

### ISSUE THREAD

**Issue by praneshvrp1396** [base4sistemas/pyescpos#21]
I am trying to print TEXTA to the left and TEXTB to the right of the same line.

TEXTA                   TEXTB

But TEXTB moves to the next line and I get to see it like,

TEXTA
                             TEXTB.

Need some help in fixing it.

**Comment by danielgoncalves** [comment]
You have to calculate the "entire line" placement for TEXTA and TEXTB based on [Columns feature](https://github.com/base4sistemas/pyescpos/blob/master/escpos/feature.py#L51).

[In this function](https://github.com/base4sistemas/satextrato/blob/master/satextrato/base.py#L384) you can see an example. There you have a function named "_bordas()" which in portuguese stands for "borders", and the arguments "esquerda" and "direita" stands for "left" and "right", which is in fact your TEXTA and TEXTB, i guess. The other arguments are "largura" (width in columns), "espacamento_minimo" (minimum gap between texts) and "favorecer_direita" (favor value on the right, when the two texts doesn't fit).

Hope you can follow the example.

**Comment by danielgoncalves** [comment]
By "borders" I actually meant "edges".
